### PR TITLE
removed android:allowBackup="true" as it could conflict with the main…

### PR DESCRIPTION
**Pull request by mightyfrog**
… application

### CODE REVIEW

**Comment by samtstern** [comment]
This is a good PR, happy to merge after the CLA is resolved.  I know it's annoying to fill out a form for a one-line change but because this repo is Google property I have to follow the procedure.

**Comment by mightyfrog** [comment]
I signed it!

**Comment by samtstern** [comment]
What email address did you use for the CLA? Just so I can check.

**Comment by mightyfrog** [comment]
mightyfrog.gc@gmail.com

**Pull request merged**
